export const tagDescriptions = {
  ARC: "Architectural Services",
  ASB: "Asbestos Abatement",
  AV: "Audio-Visual Installations",
  CAB: "Cabinets",
  CAR: "Carpentry and Woodwork",
  CKE: "Commercial Kitchen Equipment",
  CLE: "Cleaners",
  CLG: "Ceiling Systems",
  CTP: "Countertops",
  CON: "Concrete and Masonry",
  CUR: "Curtain Wall Systems",
  DB: "Design and Build Contractors",
  DEM: "Demolition",
  DRY: "Drywall and Plaster",
  DTCM: "Door and Trim CM",
  ELEC: "Electrical",
  ELEV: "Elevator and Escalator Installation",
  ENG: "Engineering Services",
  ENV: "Environmental Contractors",
  ENVC: "Environmental Cleanup and Remediation",
  EXC: "Excavation",
  FAC: "Facade and Cladding Contractors",
  FIN: "Finishing",
  FLR: "Flooring",
  FPS: "Fire Protection and Sprinkler Systems",
  FRM: "Framing",
  GLS: "Glass and Glazing",
  GRD: "Grading and Paving",
  HVAC: "HVAC",
  HIS: "Historic Restoration",
  IEQ: "Industrial Equipment Installation",
  INS: "Insulation",
  LND: "Landscaping and Hardscaping",
  LEAD: "Lead Paint Removal",
  LOG: "Logistics and Material Handling",
  LMEQ: "Laboratory and Medical Equipment",
  PNT: "Painting",
  PLM: "Plumbing",
  REN: "Renovation and Restoration",
  REM: "Remodeling",
  ROF: "Roofing",
  SEC: "Security Systems",
  SID: "Siding",
  SOL: "Solar Energy and Green Building Solutions",
  SPC: "Specialty Coatings and Sealants",
  SPEQ: "Specialty Equipment Contractors",
  STL: "Steel and Metal Fabrication",
  TLE: "Tile and Stone Installation",
  UTIL: "Utility Contractors",
  WARE: "Warehouse Setup",
  WND: "Windows and Doors",
  WTR: "Waterproofing and Mold Remediation",
  OTH: "Other",
};

export const supplierTagDescriptions = {
  ACOUST: "Acoustic Materials",
AGG: "Aggregate Suppliers",
BRK: "Brick Suppliers",
CABL: "Cabling and Networking Supplies",
CAB: "Cabinets",
CKE: "Commercial Kitchen Equipment",
CMP: "Concrete Materials and Ready-Mix Suppliers",
CNTN: "Containers and Storage Solutions",
CONV: "Construction Vehicles and Equipment Rental",
CNVY: "Conveyors and Lifting Equipment",
DRY: "Drywall and Plaster Materials",
ELE: "Electrical Supplies and Equipment",
ENG: "Engineered Wood Products",
ENV: "Environmental and Erosion Control Suppliers",
FAB: "Fabrication and Welding Supplies",
FRM: "Formwork and Shuttering Materials",
FURN: "Furniture and Fixtures Suppliers",
GLAS: "Glass and Mirror Suppliers",
GRDN: "Gardening and Landscaping Supplies",
HRDW: "Hardware and Fasteners",
HVACS: "HVAC Supplies and Equipment",
INSUL: "Insulation Materials",
LGT: "Lighting Fixtures and Supplies",
LMEQ: "Laboratory and Medical Equipment",
LOG: "Logistics and Material Handling",
LUM: "Lumber and Wood Suppliers",
MAR: "Marble and Granite Suppliers",
MTL: "Metal and Steel Suppliers",
PAIN: "Paint and Coatings Suppliers",
PLMB: "Plumbing Supplies and Fixtures",
PLST: "Plastic and Composite Materials",
RFMS: "Roofing Materials",
SAF: "Safety Equipment and PPE Suppliers",
SAND: "Sand and Gravel Suppliers",
SEAL: "Sealants and Adhesives",
SPEQ: "Specialty Equipment Contractors",
STON: "Stone and Tile Suppliers",
SURF: "Surface Preparation and Coatings",
TAP: "Tapes and Adhesives",
TEMP: "Temporary Fencing and Barricades",
TOOLS: "Tools and Equipment Rental",
WARE: "Warehouse Setup",
WALL: "Wall Systems and Panels",
WNDW: "Window and Door Suppliers",
WTRS: "Water Supply and Drainage Systems",
};
